formatting, refactored main, made some changes to prefix system and ready
CoreyShupe/Synthesis pull request #2
Opened 2021-09-15 22:21 UTC by orvitpng

2021-09-15 23:01 UTC, CoreyShupe requested changes

2021-09-15 23:01 UTC, CoreyShupe commented on src/commands/SyncCommand.ts
> +    _start: number,
just remove this field if it's unused

2021-09-15 23:01 UTC, CoreyShupe commented on src/main.ts
>  client.commands.add(SyncCommand);
should we do this in the synthesis client if we're refactoring main under a function like `registerSynthesisCommands`

2021-09-15 23:01 UTC, CoreyShupe commented on src/main.ts
>  client.connect(config.discord.secret, [
maybe make a function in synthesis client like `start()` or just `connect()` inside of the SynthesisClient class, that way we can really clean up main

2021-09-15 23:03 UTC, DebitCardz commented on src/commands/SyncCommand.ts
> +    _start: number,
Ah yeah I removed the process time from the embed but forgot to remove the parameter.

2021-09-15 23:04 UTC, orvitpng commented on src/main.ts
>  client.commands.add(SyncCommand);
Huh?

2021-09-15 23:04 UTC, orvitpng commented on src/main.ts
>  client.connect(config.discord.secret, [
ill probably do it like my bot's code, gimme a bit

2021-09-15 23:08 UTC, CoreyShupe commented on src/main.ts
>  client.commands.add(SyncCommand);
remove the raw client calls from main and put them inside of functions in the client class

2021-09-15 23:10 UTC, orvitpng commented on src/main.ts
>  client.commands.add(SyncCommand);
look at my new commit

2021-09-16 02:02 UTC, orvitpng commented
@CoreyShupe here ya go

2021-09-16 02:14 UTC, CoreyShupe commented on src/client.ts
> -    ) as Config;
does this not give a Type Error by removing this?

2021-09-16 02:16 UTC, orvitpng commented on src/client.ts
> -    ) as Config;
you don't have to be verbose about it

2021-09-16 02:17 UTC, merged